In [1]:
import numpy as np

zomato = np.array([4.2, 4.5, 3.8, 4.7, 4.0])
swiggy = np.array([4.0, 4.3, 3.9, 4.6, 4.1])

result = np.concatenate((zomato, swiggy))

print(result)

[4.2 4.5 3.8 4.7 4.  4.  4.3 3.9 4.6 4.1]


In [2]:
import numpy as np

post1 = np.array([100, 120, 150, 130, 180, 200, 220])
post2 = np.array([80, 110, 140, 160, 170, 190, 210])
post3 = np.array([90, 100, 130, 150, 160, 180, 200])

result = np.vstack((post1, post2, post3))

print(result)

[[100 120 150 130 180 200 220]
 [ 80 110 140 160 170 190 210]
 [ 90 100 130 150 160 180 200]]


In [3]:
import numpy as np

product_ids = np.array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112])

result = np.array_split(product_ids, 5)

for part in result:
    print(part)
    print("Shape:", part.shape)

[101 102 103]
Shape: (3,)
[104 105 106]
Shape: (3,)
[107 108]
Shape: (2,)
[109 110]
Shape: (2,)
[111 112]
Shape: (2,)


In [4]:
import numpy as np

messages = np.array([
    [20, 15, 30, 25, 18, 22, 28],
    [10, 12, 15, 8, 14, 11, 13],
    [35, 30, 28, 40, 32, 38, 35]
])

new_user = np.array([18, 20, 15, 22, 19, 25, 21])

messages = np.insert(messages, 3, new_user, axis=0)

total_messages = messages.sum(axis=1)

least_user = np.argmin(total_messages)

messages = np.delete(messages, least_user, axis=0)

print(messages)

[[20 15 30 25 18 22 28]
 [35 30 28 40 32 38 35]
 [18 20 15 22 19 25 21]]


In [5]:
import numpy as np

views = np.array([1000, 2500, 5000, 7500, 10000])

view_array = views.view()
copy_array = views.copy()

view_array[0] = 9999
copy_array[0] = 8888

print("Original:", views)
print("View:", view_array)
print("Copy:", copy_array)

Original: [ 9999  2500  5000  7500 10000]
View: [ 9999  2500  5000  7500 10000]
Copy: [ 8888  2500  5000  7500 10000]
