In [1]:
import numpy as np

my_likes = np.array([120, 250, 180, 300, 220, 350, 400])

friend_likes = np.array([100, 200, 210, 250, 180, 300, 380])

combined = np.add(my_likes, friend_likes)

difference = np.subtract(my_likes, friend_likes)

print("My Likes:", my_likes)
print("Friend's Likes:", friend_likes)
print("Combined Likes:", combined)
print("Difference:", difference)

My Likes: [120 250 180 300 220 350 400]
Friend's Likes: [100 200 210 250 180 300 380]
Combined Likes: [220 450 390 550 400 650 780]
Difference: [ 20  50 -30  50  40  50  20]


In [2]:
import numpy as np

prices = np.array([250, 180, 300, 150, 220])

discounted_prices = np.multiply(prices, 0.9)

final_bill = np.sum(discounted_prices)

print("Original Prices:", prices)
print("Prices After 10% Discount:", discounted_prices)
print("Final Bill Amount:", final_bill)

Original Prices: [250 180 300 150 220]
Prices After 10% Discount: [225. 162. 270. 135. 198.]
Final Bill Amount: 990.0


In [3]:
import numpy as np

steps = np.array([
    5000, 6500, 7000, 4500, 8000,
    6000, 7500, 5500, 9000, 6200,
    4800, 7100, 6800, 5200, 8500,
    7300, 6400, 5900, 8100, 5600,
    6900, 7700, 4300, 9200, 6100,
    7400, 6700, 5800, 8800, 7000
])

print("Mean Steps:", np.mean(steps))
print("Median Steps:", np.median(steps))
print("Standard Deviation:", np.std(steps))
print("Maximum Steps:", np.max(steps))

Mean Steps: 6693.333333333333
Median Steps: 6750.0
Standard Deviation: 1296.1309947515167
Maximum Steps: 9200


In [4]:
import numpy as np

np.random.seed(42)

ratings = np.random.uniform(1, 5, 10)

print("Original Ratings:")
print(ratings)

print("\nRounded Ratings:")
print(np.round(ratings))

print("\nFloor Ratings:")
print(np.floor(ratings))

print("\nCeil Ratings:")
print(np.ceil(ratings))

Original Ratings:
[2.49816048 4.80285723 3.92797577 3.39463394 1.62407456 1.62397808
 1.23233445 4.46470458 3.40446005 3.83229031]

Rounded Ratings:
[2. 5. 4. 3. 2. 2. 1. 4. 3. 4.]

Floor Ratings:
[2. 4. 3. 3. 1. 1. 1. 4. 3. 3.]

Ceil Ratings:
[3. 5. 4. 4. 2. 2. 2. 5. 4. 4.]


In [5]:
import numpy as np

skips = np.array([
    1, 0, 1, 0, 0,
    1, 0, 1, 0, 0,
    1, 0, 0, 1, 0,
    0, 1, 0, 1, 0
])

# Calculate percentage of songs skipped
skip_percentage = np.mean(skips) * 100

# Find the 75th percentile
skip_75th_percentile = np.percentile(skips, 75)

print("Skip Percentage:", skip_percentage, "%")
print("75th Percentile of Skips:", skip_75th_percentile)

Skip Percentage: 40.0 %
75th Percentile of Skips: 1.0
