In [1]:
import numpy as np

prices = np.array([199, 299, 399, 499, 599])

print("First Price:", prices[0])
print("Last Price:", prices[-1])

First Price: 199
Last Price: 599


In [2]:
import numpy as np

scores = np.array([
    [80, 85, 90, 75, 88],
    [70, 82, 95, 80, 91],
    [88, 76, 84, 92, 89]
])

print(scores[:, 1:4])

[[85 90 75]
 [82 95 80]
 [76 84 92]]


In [3]:
import numpy as np

ratings = np.array([4.5, 3.8, 4.2, 2.9, 5.0, 3.5])

print(ratings[-3:])

[2.9 5.  3.5]


In [4]:
import numpy as np

numbers = np.arange(1, 21)

print(numbers[1::3])

[ 2  5  8 11 14 17 20]


In [5]:
import numpy as np

prices = np.array([250, 650, 450, 800, 350, 550, 900])

print(prices[prices > 500])

[650 800 550 900]


In [6]:
import numpy as np

scores = np.array([210, 180, 195, 220, 205, 175])

indices = np.where(scores > 200)

print(indices[0])

[0 3 4]
