In [5]:
import numpy as np
likes = np.array([120, 250, 180, 320, 150, 400, 275])
print("Array:", likes)
print("ndim:", likes.ndim)
print("shape:", likes.shape)
print("size:", likes.size)
print("dtype:", likes.dtype)
print("itemsize:", likes.itemsize)
print("nbytes:", likes.nbytes)

Array: [120 250 180 320 150 400 275]
ndim: 1
shape: (7,)
size: 7
dtype: int64
itemsize: 8
nbytes: 56


In [6]:
import numpy as np
steps = np.array([
    [3000, 4000],
    [2500, 3500],
    [4000, 4500],
    [3200, 3800],
    [2800, 4200]
])

print("Original Array:")
print(steps)
print("Original Shape:", steps.shape)


steps_1d = steps.reshape(10)

print("\n1D Array:")
print(steps_1d)
print("1D Shape:", steps_1d.shape)

steps_2d = steps_1d.reshape(5, 2)

print("\nBack to 2D Array:")
print(steps_2d)
print("2D Shape:", steps_2d.shape)

Original Array:
[[3000 4000]
 [2500 3500]
 [4000 4500]
 [3200 3800]
 [2800 4200]]
Original Shape: (5, 2)

1D Array:
[3000 4000 2500 3500 4000 4500 3200 3800 2800 4200]
1D Shape: (10,)

Back to 2D Array:
[[3000 4000]
 [2500 3500]
 [4000 4500]
 [3200 3800]
 [2800 4200]]
2D Shape: (5, 2)


In [7]:
import numpy as np

prices = np.array([
    [120, 150, 200, 180],
    [100, 250, 130, 170],
    [220, 140, 190, 160]
])

print("Original Array:")
print(prices)



ravel_result = prices.ravel()

print("\nUsing ravel():")
print(ravel_result)



flatten_result = prices.flatten()

print("\nUsing flatten():")
print(flatten_result)

resize_result = prices.copy()
resize_result.resize(4, 3)

print("\nUsing resize():")
print(resize_result)

Original Array:
[[120 150 200 180]
 [100 250 130 170]
 [220 140 190 160]]

Using ravel():
[120 150 200 180 100 250 130 170 220 140 190 160]

Using flatten():
[120 150 200 180 100 250 130 170 220 140 190 160]

Using resize():
[[120 150 200]
 [180 100 250]
 [130 170 220]
 [140 190 160]]


In [8]:
import numpy as np

playlist = np.array([
    [20, 15, 10],
    [12, 18, 8],
    [25, 10, 15]
])

print("Original Playlist Grid:")
print(playlist)

transpose_t = playlist.T

print("\nUsing T:")
print(transpose_t)


transpose_function = np.transpose(playlist)

print("\nUsing np.transpose():")
print(transpose_function)

Original Playlist Grid:
[[20 15 10]
 [12 18  8]
 [25 10 15]]

Using T:
[[20 12 25]
 [15 18 10]
 [10  8 15]]

Using np.transpose():
[[20 12 25]
 [15 18 10]
 [10  8 15]]


In [9]:
import numpy as np


ratings = np.array([
    4, 5, 3, 4, 2,
    5, 4, 3, 5, 4,
    2, 3, 4, 5, 3
])

print("Original 1D Array:")
print(ratings)
print("Shape:", ratings.shape)


ratings_2d = ratings.reshape(3, 5)

print("\n3x5 Array:")
print(ratings_2d)
print("Shape:", ratings_2d.shape)

ratings_1d = ratings_2d.flatten()

print("\nBack to 1D using flatten():")
print(ratings_1d)
print("Shape:", ratings_1d.shape)


Original 1D Array:
[4 5 3 4 2 5 4 3 5 4 2 3 4 5 3]
Shape: (15,)

3x5 Array:
[[4 5 3 4 2]
 [5 4 3 5 4]
 [2 3 4 5 3]]
Shape: (3, 5)

Back to 1D using flatten():
[4 5 3 4 2 5 4 3 5 4 2 3 4 5 3]
Shape: (15,)
